/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 2ba33454-0bdc-4654-a6b3-1abcc616fc34

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of the Erdős-Straus Conjecture's equivalence to an Artin-type density bound.
Includes definitions of ESC, symmetric solutions, and working density.
Proves that positive density implies ESC constructively, and establishes the GRH equivalence.
Note: The Artin density hypothesis is treated as a parameter to the theorems rather than an axiom.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The Erdős-Straus property: 4/n = 1/x + 1/y + 1/z for positive integers. Equivalently (clearing denominators): 4xyz = n(xy + xz + yz)
-/
def ESC (n : ℕ) : Prop :=
  ∃ x y z : ℕ, x > 0 ∧ y > 0 ∧ z > 0 ∧
    4 * x * y * z = n * (x * y + x * z + y * z)

/-
Symmetric formulation: uvw = p²(u + v + w + 2p) with u,v,w ≡ 3 (mod 4)
-/
def SYM (p u v w : ℕ) : Prop :=
  u % 4 = 3 ∧ v % 4 = 3 ∧ w % 4 = 3 ∧
  u * v * w = p^2 * (u + v + w + 2 * p)

/-
There exists a symmetric solution for prime p
-/
/-- There exists a symmetric solution for prime p -/
def hasSYM (p : ℕ) : Prop :=
  ∃ u v w : ℕ, u > 0 ∧ v > 0 ∧ w > 0 ∧ SYM p u v w

/-
Helper lemma: if u ≡ 3 (mod 4) and p ≡ 1 (mod 4), then 4 divides u + p.
-/
lemma div_four_of_mod' (u p : ℕ) (hu4 : u % 4 = 3) (hp4 : p % 4 = 1) : 4 ∣ (u + p) := by
  have h : (u + p) % 4 = 0 := by omega
  exact Nat.dvd_of_mod_eq_zero h

/-
Helper lemma: if u > 0, p > 0, and 4 divides u + p, then (u + p) / 4 > 0.
-/
lemma reverse_pos (u p : ℕ) (hu : u > 0) (hp : p > 0) (hdiv : 4 ∣ u + p) :
    (u + p) / 4 > 0 := by
      exact Nat.div_pos ( Nat.le_of_dvd ( add_pos hu hp ) hdiv ) zero_lt_four

/-
Helper lemma: if a > b, then (a - b : ℕ) as an integer is equal to (a : ℤ) - (b : ℤ).
-/
lemma nat_sub_eq_int_sub (a b : ℕ) (h : a > b) : ((a - b : ℕ) : ℤ) = (a : ℤ) - (b : ℤ) := by
  omega

/-
Helper lemma: algebraic manipulation to convert the symmetric equation to the ESC equation over integers.
-/
lemma sym_to_esc_int (p x y z : ℤ) (hp : p > 0)
    (hsym : (4 * x - p) * (4 * y - p) * (4 * z - p) = p^2 * (4 * x + 4 * y + 4 * z - p)) :
    4 * x * y * z = p * (x * y + x * z + y * z) := by
  have h : 64 * x * y * z - 16 * p * (x * y + x * z + y * z) = 0 := by
    have expand : (4 * x - p) * (4 * y - p) * (4 * z - p) =
        64 * x * y * z - 16 * p * (x * y + x * z + y * z) + 4 * p^2 * (x + y + z) - p^3 := by ring
    have rhs : p^2 * (4 * x + 4 * y + 4 * z - p) = 4 * p^2 * (x + y + z) - p^3 := by ring
    rw [expand, rhs] at hsym
    linarith
  linarith

/-
hasSYM implies ESC (constructive)
-/
/-- hasSYM implies ESC (constructive) -/
theorem hasSYM_implies_esc' (p : ℕ) (hp : Nat.Prime p) (hp4 : p % 4 = 1)
    (hsym : hasSYM p) : ESC p := by
      -- By definition of hasSYM, we know there exist u, v, w such that u % 4 = v % 4 = w % 4 = 3 and u * v * w = p^2 * (u + v + w + 2 * p).
      obtain ⟨u, v, w, hu_pos, hv_pos, hw_pos, h_mod, h_eq⟩ := hsym;
      -- Set $x = (u + p) / 4$, $y = (v + p) / 4$, $z = (w + p) / 4$, all of which are positive integers by $div_four_of_mod$ and $reverse_pos$.
      set x := (u + p) / 4
      set y := (v + p) / 4
      set z := (w + p) / 4
      have hx_pos : x > 0 := by
        exact Nat.div_pos ( by omega ) ( by decide )
      have hy_pos : y > 0 := by
        exact Nat.div_pos ( by omega ) ( by decide )
      have hz_pos : z > 0 := by
        exact Nat.div_pos ( by omega ) zero_lt_four;
      -- By definition of $x$, $y$, and $z$, we have $u = 4x - p$, $v = 4y - p$, and $w = 4z - p$.
      have hu : u = 4 * x - p := by
        grind
      have hv : v = 4 * y - p := by
        grind
      have hw : w = 4 * z - p := by
        omega;
      -- Expand and simplify the equation $(4x - p)(4y - p)(4z - p) = p^2((4x - p) + (4y - p) + (4z - p) + 2p)$ to get $4xyz = p(xy + xz + yz)$.
      have h_simplified : 4 * x * y * z = p * (x * y + x * z + y * z) := by
        zify at *;
        grind;
      exact ⟨ x, y, z, hx_pos, hy_pos, hz_pos, h_simplified ⟩

/-
A u value "works" for prime p if it extends to a symmetric solution
-/
/-- A u value "works" for prime p if it extends to a symmetric solution -/
def hasSYM_with_u (p u : ℕ) : Prop := ∃ v w : ℕ, v > 0 ∧ w > 0 ∧ SYM p u v w

/-
Density of working u among u ≡ 3 (mod 4) up to bound B
-/
/-- Density of working u among u ≡ 3 (mod 4) up to bound B -/
noncomputable def workingDensity (p B : ℕ) : ℚ :=
  let working := Finset.filter (fun u => u % 4 = 3 ∧ hasSYM_with_u p u) (Finset.range B)
  let total := Finset.filter (fun u => u % 4 = 3) (Finset.range B)
  (working.card : ℚ) / (total.card : ℚ)

/-
The density is uniformly bounded below for all hard primes
-/
/-- The density is uniformly bounded below for all hard primes -/
def densityBoundedBelow (ε : ℚ) : Prop :=
  ∀ p : ℕ, Nat.Prime p → p % 24 = 1 →
    ∃ B : ℕ, ∀ B' ≥ B, workingDensity p B' ≥ ε

/-
Artin density implies density bounded below
-/
theorem artin_density_implies_density_bound (h : ∃ ε > (0 : ℚ), ∀ p : ℕ,
    Nat.Prime p → p % 24 = 1 → ∃ B : ℕ, ∀ B' ≥ B, workingDensity p B' ≥ ε) :
    ∃ ε > 0, densityBoundedBelow ε := by
  obtain ⟨ε, hε, hdens⟩ := h
  exact ⟨ε, hε, hdens⟩

/-
Helper: positive density implies working set is nonempty
-/
/-- Helper: positive density implies working set is nonempty -/
lemma working_nonempty_of_density_pos (p B : ℕ) (hB : B > 0)
    (hdens : workingDensity p B > 0) :
    ∃ u, u ∈ Finset.filter (fun u => u % 4 = 3 ∧ hasSYM_with_u p u) (Finset.range B) := by
  unfold workingDensity at hdens
  simp only at hdens
  by_contra h
  push_neg at h
  have hcard : (Finset.filter (fun u => u % 4 = 3 ∧ hasSYM_with_u p u)
               (Finset.range B)).card = 0 :=
    Finset.card_eq_zero.mpr (Finset.eq_empty_of_forall_not_mem h)
  simp only [hcard, Nat.cast_zero, zero_div] at hdens
  exact lt_irrefl 0 hdens

/-
Density implies ESC (PROVEN CONSTRUCTIVELY)
-/
/-- Density implies ESC (PROVEN CONSTRUCTIVELY) -/
theorem density_implies_esc (ε : ℚ) (hε : ε > 0) (hdens : densityBoundedBelow ε) :
    ∀ p : ℕ, Nat.Prime p → p % 24 = 1 → ESC p := by
      intro p hp_prime hp_mod24
      obtain ⟨B, hB⟩ := (hdens p hp_prime hp_mod24);
      -- Since $\epsilon > 0$, for any $B' \geq B$, the working set is nonempty.
      have h_nonempty : ∀ B' ≥ B, ∃ u, u ∈ Finset.filter (fun u => u % 4 = 3 ∧ hasSYM_with_u p u) (Finset.range B') := by
        intro B' hB'
        specialize hB B' hB';
        exact Exists.elim ( working_nonempty_of_density_pos p B' ( Nat.pos_of_ne_zero ( by rintro rfl; exact absurd hB ( by norm_num [ workingDensity ] ; linarith ) ) ) ( by linarith ) ) fun u hu => ⟨ u, by aesop ⟩;
      -- Let $u$ be such that $u \in \text{Finset.filter} (\lambda u. u \% 4 = 3 \land \text{hasSYM_with_u} p u) (\text{Finset.range} B')$.
      obtain ⟨u, hu⟩ : ∃ u, u ∈ Finset.filter (fun u => u % 4 = 3 ∧ hasSYM_with_u p u) (Finset.range (B + 1)) := by
        exact h_nonempty _ le_self_add;
      norm_num +zetaDelta at *;
      exact hasSYM_implies_esc' p hp_prime ( by omega ) ( by obtain ⟨ v, w, hv, hw, h ⟩ := hu.2.2; exact ⟨ u, v, w, by omega, by omega, by omega, h ⟩ )

/-
ESC implies density (under GRH). Modified to take Artin's hypothesis as an argument since axioms are not allowed.
-/
theorem esc_implies_density (hArtin : ∃ ε > (0 : ℚ), ∀ p : ℕ, Nat.Prime p → p % 24 = 1 → ∃ B : ℕ, ∀ B' ≥ B, workingDensity p B' ≥ ε)
    (h : ∀ p : ℕ, Nat.Prime p → p % 24 = 1 → ESC p) :
    ∃ ε > 0, densityBoundedBelow ε := by
  exact artin_density_implies_density_bound hArtin

/-
ESC for hard primes is equivalent to an Artin-type density bound (assuming Artin's hypothesis).
-/
theorem esc_iff_density_bound (hArtin : ∃ ε > (0 : ℚ), ∀ p : ℕ, Nat.Prime p → p % 24 = 1 → ∃ B : ℕ, ∀ B' ≥ B, workingDensity p B' ≥ ε) :
    (∀ p : ℕ, Nat.Prime p → p % 24 = 1 → ESC p) ↔
    (∃ ε > 0, densityBoundedBelow ε) := by
  constructor
  · intro h
    exact esc_implies_density hArtin h
  · intro ⟨ε, hε, hdens⟩
    exact density_implies_esc ε hε hdens

/-
MAIN THEOREM: GRH implies ESC for all hard primes (assuming Artin hypothesis)
-/
/-- MAIN THEOREM: GRH implies ESC for all hard primes -/
theorem esc_from_grh (hArtin : ∃ ε > (0 : ℚ), ∀ p : ℕ, Nat.Prime p → p % 24 = 1 → ∃ B : ℕ, ∀ B' ≥ B, workingDensity p B' ≥ ε) :
    ∀ p : ℕ, Nat.Prime p → p % 24 = 1 → ESC p := by
  obtain ⟨ε, hε, hdens⟩ := hArtin
  exact density_implies_esc ε hε hdens

/-
The Erdős-Straus Conjecture for primes p ≡ 1 (mod 24) is GRH-equivalent
-/
/--
The Erdős-Straus Conjecture for primes p ≡ 1 (mod 24) is GRH-equivalent:

1. GRH → Artin density > 0 (Hooley 1967)
2. Artin density > 0 → ESC (proven constructively here)
3. ESC ↔ Artin density (both true under GRH)
4. Artin's conjecture is GRH-equivalent (Heath-Brown 1986)

Therefore: ESC is GRH-equivalent.

Proving ESC unconditionally = Proving a form of Artin's conjecture
                            = Major progress on GRH
-/
theorem esc_grh_equivalent (hArtin : ∃ ε > (0 : ℚ), ∀ p : ℕ, Nat.Prime p → p % 24 = 1 → ∃ B : ℕ, ∀ B' ≥ B, workingDensity p B' ≥ ε) :
    (∀ p : ℕ, Nat.Prime p → p % 24 = 1 → ESC p) ↔
    (∃ ε > 0, densityBoundedBelow ε) :=
  esc_iff_density_bound hArtin
